In [1]:
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df = pd.read_csv("calFire_cleaned.csv",skiprows = 0)
df.head(5)

,incident_county,incident_acres_burned,incident_cooperating_agencies,fire_started,fire_extinguished,days_of_fire
0,Shasta,37.0,Shasta-Trinity National Forest,2017-10-31,2018-01-09,70.0
1,San Diego,122.0,CAL FIRE San Diego Unit,2009-05-24,2009-05-25,1.0
2,Inyo,406.0,"CAL FIRE San Bernardino Unit, Inyo County Sher...",2013-02-24,2013-02-28,4.0
3,San Bernardino,30.0,San Bernardino National Forest,2013-04-20,2013-04-22,2.0
4,Madera,274.0,CAL FIRE Madera-Mariposa-Merced Unit,2013-04-30,2013-05-01,1.0

In [3]:
df['fire_started'] = pd.to_datetime(df['fire_started'], format='%Y-%m-%d')

In [4]:
df['fire_extinguished'] = pd.to_datetime(df['fire_extinguished'], format='%Y-%m-%d')

In [40]:
df.dropna(
    axis=0,
    how='any',
    inplace=True
)
df.empty
df.drop_duplicates()
df.to_csv('calFire_cleaned.csv',index=False)

In [39]:
#df.groupby(['incident_county'], as_index=False)["incident_acres_burned"].mean()
df[['incident_county','incident_acres_burned']].groupby('incident_county').sum().sort_values(by = 'incident_acres_burned', 
ascending = True)
#df[['incident_county','incident_acres_burned']].groupby(['incident_county']).sum()

#df[df['incident_county']== 'San Diego']['incident_acres_burned'].sum()
#df.groupby('incident_county')['incident_acres_burned'].unique()

                                                    incident_acres_burned
incident_county
Alpine                                                                0.0
Sonoma, Solano, Lake, Colusa                                         28.0
San Mateo                                                           153.0
El Dorado, Sacramento                                               163.0
Glenn, Mendocino                                                    211.0
Imperial                                                            275.0
Santa Cruz                                                          418.0
Del Norte                                                           537.0
Colusa                                                              730.0
State of Oregon                                                    1301.0
Amador                                                             1709.0
Monterey, San Luis Obispo                                          1816.0
Sutter                                                             2850.0
Napa                                                               3623.0
Glenn                                                              3711.0
Calaveras                                                          3926.0
San Benito                                                         3933.0
State of Nevada                                                    4140.0
Amador, El Dorado                                                  4240.0
Napa, Lake                                                         4300.0
Kern, Ventura                                                      4346.0
Nevada                                                             4904.0
Alameda                                                            5151.0
Marin                                                              5211.0
El Dorado, Placer                                                  5646.0
Contra Costa                                                       5862.0
Solano                                                             6612.0
Sacramento                                                         7132.0
Stanislaus                                                         8128.0
Merced                                                            10348.0
...                                                                   ...
San Diego                                                         64735.0
Orange                                                            69880.0
Tulare                                                            77054.0
Riverside                                                         81193.0
Siskiyou, Modoc                                                   83261.0
Santa Cruz, San Mateo                                             86509.0
Napa, Yolo                                                        90288.0
San Bernardino                                                    90531.0
Lake                                                              93621.0
Modoc                                                             95926.0
Los Angeles, Ventura                                              96949.0
San Luis Obispo                                                   97570.0
El Dorado                                                        100778.0
Sonoma                                                           102428.0
Kern                                                             121887.0
Los Angeles                                                      125716.0
Monterey                                                         145456.0
Shasta                                                           155445.0
Napa, Sonoma                                                     160847.0
Butte                                                            188799.0
Lassen                                                           191829.0
Mariposa                                                         197986.0
Fresno                                                           245359.0
Santa Barbara, Ventura                                           281893.0
Siskiyou                                                         285275.0
Shasta, Trinity                                                  292962.0
Tuolumne                                                         299038.0
Santa Clara, Alameda, Contra Costa, San Joaquin...               396624.0
Colusa, Glenn, Lake, Mendocino                                   410203.0
Mendocino, Humboldt, Trinity, Tehama, Glenn, La...              1032648.0

[82 rows x 1 columns]